const PREFIX_CUSTOMER = 'CUST'
const PREFIX_LEASING = 'LEA'
const PREFIX_CAR = 'CAR'
const PREFIX_INVOICE = 'INV'

const ALL_PREFIX = {
	PREFIX_CAR,
	PREFIX_CUSTOMER,
	PREFIX_INVOICE,
	PREFIX_LEASING,
}

const SUCCESS = 'SUCCESS'
const INSERTED = 'INSERTED'
const UNAUTHORIZED = 'UNAUTHORIZED'
const FORBIDDEN = 'FORBIDDEN'
const ERROR = 'ERROR'

const ALL_RESPONSE = {
	SUCCESS,
	INSERTED,
	UNAUTHORIZED,
	FORBIDDEN,
	ERROR,
}

module.exports = {
	ALL_PREFIX,
	ALL_RESPONSE,
}
